import {StyleSheet,Dimensions,Platform} from 'react-native';
const height = Dimensions.get('window').height;
const width = Dimensions.get('window').width;
export default StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: "column",
        backgroundColor:"#FFFFFF",
    },  
    content:{
        paddingHorizontal:16,
        paddingVertical:20,
        borderRadius:10,
    },
    playbtn:{
        width:width*0.27,
        height:height*0.15,        
    },
    image:{
        height:(height-56)*0.2,
    },
    loadingimg:{
        height:150,
        width:150,
        overflow:'hidden',        
    },
    conferbox:{
        paddingHorizontal:20,
        paddingVertical:26,
    },
    time:{
        color:"#F35174",
        fontSize:14
    },
    title:{
        color:'white',
        fontSize:18,
        marginBottom:10
    },
    des:{
        color:'white',
        fontSize:13
    },
    sessionheader:{
        height:50,
        flexDirection:'row',
        borderBottomWidth:1,
        borderBottomColor:'#A1A1A11A'
    },
    tabbtn:{
        width:width/2,
        justifyContent:'space-between',
        alignItems:'center'
    },
    tabtext:{
        color:'#AAAAAA',
        fontSize:16
    },
    tabactivetext:{
        color:'#F35174',
        fontSize:16
    },
    activetab:{
        width:(width/2)*0.34,
        justifyContent:'center',
        alignItems:'center',
        borderBottomColor:'#F35174',
        borderBottomWidth:2
    },
    seslistwrap:{
        paddingHorizontal:16,
        borderBottomWidth:1,
        borderBottomColor:'#A1A1A11A'
    },
    seslist:{
        paddingHorizontal:10,
        paddingVertical:26,
        flexDirection:'row',
        justifyContent:'space-between',

    },
    lang:{
        color:"#2B292A",
        fontSize:14,
        fontWeight:'700',
        marginRight:11
    },
    sesplay:{
        width:25,
        height:25
    },
    soundbox:{
        flex:1,
        paddingHorizontal:16,
        marginVertical:20,
        flexDirection:'row',
        alignItems:'flex-end'
    },
    soundimg:{
        width:20,
        height:16,
        resizeMode:'cover',
        marginRight:8,
    },
    soundView:{
        width:width-18-48,
        height:14,
        flexDirection:'row',
    },
    durationView:{
        width:width-18-48,
        height:14,
        flexDirection:'row',
        alignItems:"center",
        justifyContent:"flex-end",
        marginRight:8,
    },
    bar:{
        width:2,
        marginRight:2,
        backgroundColor:"#AAAAAA"
    },
    activebar:{
        width:2,
        marginRight:2,
        backgroundColor:"#F35174"
    },
    databox:{
        flexDirection:"row",
    },
    volume:{
        color:'#AAAAAA',
        fontSize:13,
    },
    playbox:{
        marginTop:50,
        justifyContent:'center',
        alignItems:"center"
    },
    transdes:{
        flexDirection:"row",
        marginBottom:55      
    },
    transtext:{
        color:'#A1A1A1',
        fontSize:14
    },
    transtit:{
        color:'#231F21',
        fontSize:18,
        fontWeight:'bold',
        marginBottom:5        
    },
    round:{
        width:6,
        height:6,
        borderRadius:6,
        marginRight:5,
        backgroundColor:'#000000'
    },
    soundAnddurationbox:{
        justifyContent:'flex-end',
        flex:1
    },
    durationbox:{
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:"center",
        paddingHorizontal:16,
    },
    txtmr:{
        color:'#000000',
        fontSize:12,
    },
    object: {
        backgroundColor: 'orange',
        width: 100,
        height: 100
      },
      loadingbtn:{
        width:110,
        height:110,
        borderRadius:110,
        backgroundColor:'#F35174',
        justifyContent:'center',
        alignItems:'center',
      },
      animationview:{
          width:width*0.27,
          height:height*0.15,
          justifyContent:'center',
          alignItems:'center',
      },
      overflowview:{    
        borderRadius:500,
        overflow:'hidden',
      }
  });
  